project_urls = {'99papers': 'https://99papers.com/',
                'bookwormlab': 'https://bookwormlab.com/',
                'essaybox': 'https://essaybox.org',
                'essayfactory': 'https://essayfactory.uk',
                'buzzessay': 'https://buzzessay.com',
                'buyessaysafe': 'https://buyessaysafe.com',
                'profortask': 'https://profortask.com',
                'homeworkstock': 'https://homeworkstock.com',
                'edubutlers': 'https://edubutlers.online',
                'smartcontentllc': 'https://smartcontentllc.com',
                'experttutors': 'https://experttutors.online',
                'edubutlers.com': 'edubutlers.com',
                'aussiewriterslab': 'aussiewriterslab.com',
                'essaybox.com': 'essaybox.com'
                }
